import { APP_TYPES } from '../../parseApps'
import { CordovaManualAnalysisReport } from './index'

export const id = 'cordova/20170726-d-z/net.jp.apps.noboruhirohara.yakei-102008-2016_05_02.apk'
export const report: CordovaManualAnalysisReport = {
  app: {
    type: APP_TYPES.cordova,
    section: '20170726-d-z',
    app: 'net.jp.apps.noboruhirohara.yakei-102008-2016_05_02.apk',
  },
  files: {
    'body/0007': { location: 'body', id: '0007', type: 'business-logic' },
    'body/0008': { location: 'body', id: '0008', type: 'http-script' },
    'head/0000': {
      location: 'head',
      id: '0000',
      type: 'bundle',
      match: [
        { name: 'monaca-cordova-loader', isGuess: true, minified: false },
        { name: 'monaca-core-utils', version: '2.0.4', isGuess: false, minified: false },
        {
          name: 'jquery',
          version: '1.9.0',
          isGuess: false,
          minified: false,
          comments: 'includes sizzle.js\n' + 'included as "monaca-jquery"',
        },
        {
          name: 'jquery-mobile',
          version: '1.3.1',
          isGuess: false,
          minified: false,
          comments: 'included as "monaca-jquery-mobile"',
        },
        {
          name: 'onsenui',
          version: '1.3.8',
          isGuess: true,
          minified: true,
          comments: 'included as "monaca-onsenui"',
        },
      ],
      comments: 'generated by framework bundler. framework called "Monaca"',
    },
    'head/0001': { location: 'head', id: '0001', type: 'business-logic' },
    'head/0002': { location: 'head', id: '0002', type: 'business-logic' },
    'head/0003': { location: 'head', id: '0003', type: 'business-logic' },
    'head/0004': { location: 'head', id: '0004', type: 'business-logic' },
    'head/0005': { location: 'head', id: '0005', type: 'business-logic' },
    'head/0006': { location: 'head', id: '0006', type: 'business-logic' },
  },
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const additionalData = {
  files: {
    'head/0000': {
      algReport: {
        comments: [
          'monaca library is missing in dataset and top1000',
          'onsenui library is missing in dataset and top1000',
          'jquery-mobile is missing in dataset and top1000',
          'angular is in candidates (i didnt manually find it, probably missed it.' +
            ' algorithm found it better than me)',
          'top candidates are - angular 23.65%, jquery - 17.14%',
          'angular@1.4.2 == angular@1.4.3 - 26.94% (same % val - 1222/4536)',
          'jquery@1.9.1 - 13.08%',
          'jquery@1.11.0 - 12.99%',
        ],
      },
    },
  },
}
