export const JS_DATA_FOLDER = 'js'
export const ANALYSIS_FOLDER = 'an'

export const FINISHED_PREPROCESSING_FILE = '_fin_pre_prerocess.json'
export const LIB_CANDIDATES_FILE = '_lib_candidates.json'
export const LIB_PREPROCESSED_CANDIDATES_FILE = '_lib_prep_candidates.json'
export const FINISHED_ANALYSIS_FILE = '_fin_analysis.json'
export const FOUND_LIBS_FILE = '_found_libs.json'
export const FOUND_LIBS_TOTALS_FILE = '_found_libs_totals.json'
export const FOUND_LIBS_REGEX_FILE = '_found_libs_with_regex.json'

export const CORDOVA_MAIN_FILE = 'index.html'
export const CORDOVA_LIB_FILE = 'libDesc.js'
export const CORDOVA_INFO_FILE = 'info.json'
export const CORDOVA_NON_PARSED_NOTICE_FILE = 'NOT_PARSED.txt'
export const CORDOVA_SIG_FILE = 'libStructure.json'
export const CORDOVA_SIM_FILE = 'sim.json'
export const CORDOVA_CAND_FILE = 'candidates.json'

export const REACT_NATIVE_MAIN_FILE = 'bundle.js'
export const REACT_NATIVE_SIG_FILE = 'sig.json'
export const REACT_NATIVE_SIM_FILE = 'sim.json'
export const REACT_NATIVE_CAND_FILE = 'candidates.json'
