export const TOTAL_LIBS = 100
export const TOTAL_LIBS_VERSIONS = 7526

export const GRAND_TOTAL_APPS = 101992

export const TOTAL_CORDOVA = 5639
export const TOTAL_REACT_NATIVE = 123
export const TOTAL = TOTAL_CORDOVA + TOTAL_REACT_NATIVE

export const TOTAL_PREPROCESSED_CORDOVA = 4736
export const TOTAL_PREPROCESSED_REACT_NATIVE = 123
export const TOTAL_PREPROCESSED = TOTAL_PREPROCESSED_CORDOVA + TOTAL_PREPROCESSED_REACT_NATIVE

export const TOTAL_ANALYSED_CORDOVA = 4736
export const TOTAL_ANALYSED_REACT_NATIVE = 0
export const TOTAL_ANALYSED = TOTAL_ANALYSED_CORDOVA + TOTAL_ANALYSED_REACT_NATIVE
