import { APP_TYPES } from '../../parseApps'
import { CordovaManualAnalysisReport } from './index'

export const id = 'cordova/random/Snowbuddy-1.2.8.apk'
export const report: CordovaManualAnalysisReport = {
  app: {
    type: APP_TYPES.cordova,
    section: 'random',
    app: 'Snowbuddy-1.2.8.apk',
  },
  files: {
    'head/0000': {
      location: 'head',
      id: '0000',
      type: 'single-lib',
      match: { name: 'jquery', version: '2.1.1', isGuess: false, minified: true },
    },
    'head/0001': {
      location: 'head',
      id: '0001',
      type: 'single-lib',
      match: {
        name: 'modernizr',
        version: '2.6.2',
        isGuess: false,
        minified: true,
        comments: 'custom build',
      },
    },
    'body/0002': {
      location: 'body',
      id: '0002',
      type: 'single-lib',
      match: { name: 'fastclick', version: '1.0.3', isGuess: false, minified: false },
    },
    'body/0003': {
      location: 'body',
      id: '0003',
      type: 'single-lib',
      match: { name: 'angular', version: '1.3.0', isGuess: false, minified: true },
    },
    'body/0004': {
      location: 'body',
      id: '0004',
      type: 'single-lib',
      match: { name: 'angular-touch', version: '1.3.0', isGuess: false, minified: true },
    },
    'body/0005': {
      location: 'body',
      id: '0005',
      type: 'single-lib',
      match: { name: 'angular-animate', version: '1.3.0', isGuess: false, minified: true },
    },
    'body/0006': {
      location: 'body',
      id: '0006',
      type: 'single-lib',
      match: { name: 'angular-local-storage', isGuess: true, minified: true },
    },
    'body/0007': {
      location: 'body',
      id: '0007',
      type: 'bundle',
      match: [{ name: 'ng-cordova plugins', isGuess: true, minified: true }],
    },
    'body/0008': {
      location: 'body',
      id: '0008',
      type: 'single-lib',
      match: { name: 'leaflet', version: '0.7.3', isGuess: false, minified: true },
    },
    'body/0009': {
      location: 'body',
      id: '0009',
      type: 'single-lib',
      match: { name: 'skycons', isGuess: true, minified: false },
    },
    'body/0010': {
      location: 'body',
      id: '0010',
      type: 'single-lib',
      match: { name: 'angular-skycons', isGuess: true, minified: false },
    },
    'body/0011': {
      location: 'body',
      id: '0011',
      type: 'single-lib',
      match: { name: 'angular-route', version: '1.3.0', isGuess: true, minified: true },
    },
    'body/0012': {
      location: 'body',
      id: '0012',
      type: 'single-lib',
      match: { name: 'hook.js', version: '1.1', isGuess: true, minified: true },
    },
    'body/0013': {
      location: 'body',
      id: '0013',
      type: 'single-lib',
      match: {
        name: 'moment',
        version: '2.8.3',
        file: '0000.json',
        isGuess: false,
        minified: false,
      },
    },
    'body/0014': {
      location: 'body',
      id: '0014',
      type: 'single-lib',
      match: { name: 'angular-moment', version: '0.8.2', isGuess: true, minified: true },
    },
    'body/0015': {
      location: 'body',
      id: '0015',
      type: 'single-lib',
      match: { name: 'osmtojson', isGuess: true, minified: true },
    },
    'body/0016': {
      location: 'body',
      id: '0016',
      type: 'single-lib',
      match: { name: 'cordova', isGuess: true, minified: false },
    },
    'body/0017': {
      location: 'body',
      id: '0017',
      type: 'single-lib',
      match: { name: 'angular-leaflet-directive', isGuess: true, minified: false },
    },
    'body/0018': {
      location: 'body',
      id: '0018',
      type: 'single-lib',
      match: { name: 'ParseServices', isGuess: true, minified: false },
    },

    'body/0019': { location: 'body', id: '0019', type: 'business-logic' },
    'body/0020': { location: 'body', id: '0020', type: 'business-logic' },
    'body/0021': { location: 'body', id: '0021', type: 'business-logic' },
    'body/0022': { location: 'body', id: '0022', type: 'business-logic' },
    'body/0023': { location: 'body', id: '0023', type: 'business-logic' },
    'body/0024': { location: 'body', id: '0024', type: 'business-logic' },
    'body/0025': { location: 'body', id: '0025', type: 'business-logic' },
    'body/0026': { location: 'body', id: '0026', type: 'business-logic' },
    'body/0027': { location: 'body', id: '0027', type: 'business-logic' },
    'body/0028': { location: 'body', id: '0028', type: 'business-logic' },
    'body/0029': { location: 'body', id: '0029', type: 'business-logic' },
    'body/0030': { location: 'body', id: '0030', type: 'business-logic' },
    'body/0031': { location: 'body', id: '0031', type: 'business-logic' },
    'body/0032': { location: 'body', id: '0032', type: 'business-logic' },
    'body/0033': { location: 'body', id: '0033', type: 'business-logic' },
    'body/0034': { location: 'body', id: '0034', type: 'business-logic' },
    'body/0035': { location: 'body', id: '0035', type: 'business-logic' },
    'body/0036': { location: 'body', id: '0036', type: 'business-logic' },
    'body/0037': { location: 'body', id: '0037', type: 'business-logic' },
    'body/0038': { location: 'body', id: '0038', type: 'business-logic' },
    'body/0039': { location: 'body', id: '0039', type: 'business-logic' },
    'body/0040': {
      location: 'body',
      id: '0040',
      type: 'single-lib',
      match: { name: 'FacebookAngularPatch', isGuess: true, minified: false },
    },
    'body/0041': { location: 'body', id: '0041', type: 'business-logic' },
    'body/0042': { location: 'body', id: '0042', type: 'business-logic' },
    'body/0043': { location: 'body', id: '0043', type: 'business-logic' },
  },
}
